
-- Function to create messages table if it doesn't exist
CREATE OR REPLACE FUNCTION public.create_messages_table_if_not_exists()
RETURNS void AS $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'messages') THEN
    CREATE TABLE public.messages (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
      sender_id TEXT NOT NULL,
      receiver_id TEXT NOT NULL,
      content TEXT NOT NULL,
      sender_role TEXT NOT NULL
    );
    
    -- Enable RLS on the messages table
    ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to create profiles table if it doesn't exist
CREATE OR REPLACE FUNCTION public.create_profiles_table_if_not_exists()
RETURNS void AS $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'profiles') THEN
    CREATE TABLE public.profiles (
      user_id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      role TEXT NOT NULL,
      profile_image TEXT
    );
    
    -- Enable RLS on the profiles table
    ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
